export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const LOAD_NEWS_SUCCESS = 'LOAD_NEWS_SUCCESS';
export const GET_EVENTS = 'GET_EVENTS';
export const SET_CALENDAR = 'SET_CALENDAR';
export const SET_NEWS_CALENDAR = 'SET_NEWS_CALENDAR';
export const GET_CALENDAR = 'GET_CALENDAR';
export const LOAD_CALENDAR_LIST_SUCCESS = 'LOAD_CALENDAR_LIST_SUCCESS';
export const LOAD_CALENDAR_NEWS_LIST_SUCCESS = 'LOAD_CALENDAR_NEWS_LIST_SUCCESS';
