export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const GET_EVENTS = 'GET_EVENTS';
export const SET_CALENDAR = 'SET_CALENDAR';
