export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const GET_EVENTS = 'GET_EVENTS';
export const SET_CALENDAR = 'SET_CALENDAR';
export const GET_CALENDAR = 'GET_CALENDAR';
